### ISSUE TITLE
WebView Plugin issue

### ISSUE THREAD

**Issue by bhagyakhatri** [PonnamKarthik/FlutterWebView#23]
For Android this library is working fine. but for iOS I am getting this exception.

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following MissingPluginException was thrown while activating platform stream on channel
flutter: ponnamkarthik/flutterwebview_stream_pagestart_0:
flutter: MissingPluginException(No implementation found for method listen on channel
flutter: ponnamkarthik/flutterwebview_stream_pagestart_0)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
flutter: <asynchronous suspension>
flutter: #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:504:29)
flutter: <asynchronous suspension>
flutter: #9      _AboutState.onWebCreated (package:wallet/ui/profile/about/about_page.dart:86:38)
flutter: #10     _FlutterNativeWebState.onPlatformCreated (package:flutter_native_web/flutter_native_web.dart:57:12)
flutter: #12     _FlutterNativeWebState.onPlatformCreated (package:flutter_native_web/flutter_native_web.dart:53:33)
flutter: #13     _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:511:14)
flutter: #24     PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart)
flutter: #35     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
flutter: (elided 42 frames from package dart:async and package dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: MissingPluginException(No implementation found for method listen on channel ponnamkarthik/flutterwebview_stream_pagefinish_0)

**Comment by vulemicom** [comment]
I hame same problem
